export const AppEvent = {
    PRELOADER_PAGE_READY: "AppEvent.PRELOADER_PAGE_READY",
    PRELOADER_PAGE_SHOWN: "AppEvent.PRELOADER_PAGE_SHOWN",
    MAIN_GAME_READY: "AppEvent.MAIN_GAME_READY",
    MAIN_GAME_SHOWN: "AppEvent.MAIN_GAME_SHOWN",
};