export const AppEvent = {
    PRELOAD_PAGE_READY: "AppEvent.PRELOAD_PAGE_READY",
    PRELOAD_PAGE_SHOWN: "AppEvent.PRELOAD_PAGE_SHOWN",
    MAIN_GAME_READY: "AppEvent.MAIN_GAME_READY",
    MAIN_GAME_SHOWN: "AppEvent.MAIN_GAME_SHOWN",
};